### ISSUE TITLE
unsubscribe from Channel

### ISSUE THREAD

**Issue by sherifnada** [BenWBrown/middrides_iOS#14]

**Comment by jabillings** [comment]
Got unsubscribing to work, HOWEVER, on the dispatcher web view it still says that there is a passenger waiting after the user has unsubscribed. Not sure if this is desired functionality but I thought I'd let you know anyway

**Comment by sherifnada** [comment]
Does this happen when the dispatcher sends the push notification through the web interface? 

When the dispatcher notifies a stop that the van is arriving, the server should automatically clear/flush all those waiting in that stop. If this is not happening, then it's a server side issue.

**Comment by jabillings** [comment]
OK, then I think it is a server side issue

**Comment by sherifnada** [comment]
Fixed on server side
